---
- name: Deploy React app on EC2
  hosts: all
  become: yes
  become_user: ubuntu  # Changed from ec2-user to ubuntu

  tasks:
    - name: Install Node.js and npm (Ubuntu)
      apt:
        name: "{{ item }}"
        state: present
        update_cache: yes
      loop:
        - nodejs
        - npm
        - git

    - name: Clone your React app
      git:
        repo: 'https://github.com/deshraj-techhub/aws-devops-handson.git'
        dest: /home/ubuntu/app
        force: yes

    - name: Install dependencies
      shell: npm install
      args:
        chdir: /home/ubuntu/app

    - name: Start the app in background
      shell: nohup npm start > /dev/null 2>&1 &
      args:
        chdir: /home/ubuntu/app